name: Node.js with NVS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build with npm
      run: npm ci
    - name: Nexus Vulnerability Scanner
      uses: sonatype/nvs-github-action@develop-with-node-modules
      with:
        email: mshevelov+13@sonatype.com
        password: admin123
        directory: ./
